name = "qcheck_bench"
version = "1.0.0"


[dependencies]
birl = ">= 1.7.1 and < 2.0.0"
gleam_stdlib = ">= 0.44.0"
prng = ">= 4.0.0 and < 5.0.0"
qcheck = { path = ".." }
youid = ">= 1.2.0 and < 2.0.0"
simplifile = ">= 2.1.0 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
